services:

  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/app  
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/postgres
    command: uvicorn app.api:app --reload --host 0.0.0.0 --port 8080 --reload

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
